# Generated by Django 5.2.5 on 2025-08-29 15:35

import apps.syjon.lib.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(2), apps.syjon.lib.validators.validate_white_space], verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='departmenttype',
            name='name_en',
            field=models.CharField(max_length=256, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2), apps.syjon.lib.validators.validate_white_space], verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='name_en',
            field=models.CharField(max_length=256, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2), apps.syjon.lib.validators.validate_white_space], verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='occupation',
            name='name_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='teacherdegree',
            name='name_en',
            field=models.CharField(max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(2), apps.syjon.lib.validators.validate_white_space], verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='teacherposition',
            name='name_en',
            field=models.CharField(max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(2), apps.syjon.lib.validators.validate_white_space], verbose_name='Name'),
        ),
    ]
