# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-08 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='departmenttype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='identitydocument',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='occupation',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='teacherdegree',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='teacherposition',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='managed_departments',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='managed_users',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
