# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-08 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtype',
            options={'ordering': ('name',), 'verbose_name': 'Typ przedmiotu', 'verbose_name_plural': 'Typy przedmiotów'},
        ),
        migrations.AlterModelOptions(
            name='key',
            options={'ordering': ('name',), 'verbose_name': 'Właściwość', 'verbose_name_plural': 'Właściwości'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('name',), 'verbose_name': 'Pokój', 'verbose_name_plural': 'Pokoje'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ('name',), 'verbose_name': 'Typ pokoju', 'verbose_name_plural': 'Typy pokojów'},
        ),
    ]
