from datetime import date

MODULE_TYPE_GENERAL_ID = 11
SUBJECT_TYPE_PRACTICE_ID = 14

SYLLABUS_TYPE_MODULE_ID = 0
SYLLABUS_TYPE_SUBJECT_ID = 1
SYLLABUS_TYPE_PRACTICE_ID = 2
SYLLABUS_TYPE_GENERAL_ID = 3

SYLLABUS_TYPE_CHOICES = [
    (SYLLABUS_TYPE_MODULE_ID, "sylabus ogólny"),
    (SYLLABUS_TYPE_SUBJECT_ID, "sylabus szczegółowy"),
    # (SYLLABUS_TYPE_PRACTICE_ID, _(u'Practice syllabus')),
]

DATE = date.today()
SYLLABUS_YEAR_FIRST = 2012
SYLLABUS_YEAR_CHOICES = [(year, "{}/{}".format(year, year+1)) for year in range(SYLLABUS_YEAR_FIRST, DATE.year + 1)]

if DATE.month < 9:
    SYLLABUS_YEAR_CHOICES = SYLLABUS_YEAR_CHOICES[:-1]

SYLLABUS_SEMESTER_I_ID = 1
SYLLABUS_SEMESTER_II_ID = 2
SYLLABUS_SEMESTER_CHOICES = [
    (SYLLABUS_SEMESTER_I_ID, 'semestr zimowy'),
    (SYLLABUS_SEMESTER_II_ID, 'semestr letni')
]

DEFAULT_SYLLABUS_TYPE = SYLLABUS_TYPE_SUBJECT_ID
DEFAULT_SYLLABUS_YEAR = (DATE.year - 1) if DATE.month < 6 else DATE.year
DEFAULT_SYLLABUS_SEMESTER = SYLLABUS_SEMESTER_II_ID if date.today().month < 6 else \
    SYLLABUS_SEMESTER_I_ID
