# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 13:56
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merovingian', '0002_auto_20160123_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='sgroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='merovingian.SGroup'),
            preserve_default=False,
        ),
    ]
