# Generated by Django 5.2.5 on 2025-08-29 15:35

import django.core.validators
from django.db import migrations, models

import apps.syjon.lib.validators


class Migration(migrations.Migration):

    dependencies = [
        ('merovingian', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name_en',
            field=models.CharField(max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(2), apps.syjon.lib.validators.validate_white_space], verbose_name='name'),
        ),
        migrations.AddField(
            model_name='courselevel',
            name='name_en',
            field=models.CharField(max_length=256, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2), apps.syjon.lib.validators.validate_white_space], verbose_name='name'),
        ),
        migrations.AddField(
            model_name='courseprofile',
            name='name_en',
            field=models.CharField(max_length=256, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2), apps.syjon.lib.validators.validate_white_space], verbose_name='name'),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='name_en',
            field=models.CharField(max_length=256, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2), apps.syjon.lib.validators.validate_white_space], verbose_name='name'),
        ),
        migrations.AddField(
            model_name='didacticoffer',
            name='name_en',
            field=models.CharField(max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(2), apps.syjon.lib.validators.validate_white_space], verbose_name='name'),
        ),
        migrations.AddField(
            model_name='merovingiansettings',
            name='value_en',
            field=models.CharField(max_length=128, null=True, verbose_name='value'),
        ),
        migrations.AddField(
            model_name='module',
            name='name_en',
            field=models.CharField(max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(2), apps.syjon.lib.validators.validate_white_space], verbose_name='name'),
        ),
        migrations.AddField(
            model_name='moduletype',
            name='name_en',
            field=models.CharField(max_length=256, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2), apps.syjon.lib.validators.validate_white_space], verbose_name='name'),
        ),
        migrations.AddField(
            model_name='sgroup',
            name='name_en',
            field=models.CharField(max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(2), apps.syjon.lib.validators.validate_white_space], verbose_name='name'),
        ),
        migrations.AddField(
            model_name='sgrouptype',
            name='name_en',
            field=models.CharField(max_length=256, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2), apps.syjon.lib.validators.validate_white_space], verbose_name='name'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(max_length=256, null=True, validators=[django.core.validators.MinLengthValidator(2), apps.syjon.lib.validators.validate_white_space], verbose_name='name'),
        ),
        migrations.AddField(
            model_name='subjectassessment',
            name='name_en',
            field=models.CharField(max_length=256, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2), apps.syjon.lib.validators.validate_white_space], verbose_name='name'),
        ),
        migrations.AddField(
            model_name='subjectdifficulty',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='subjecttype',
            name='name_en',
            field=models.CharField(max_length=256, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2), apps.syjon.lib.validators.validate_white_space], verbose_name='name'),
        ),
    ]
