# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 14:45
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merovingian', '0004_auto_20160203_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleproperties',
            name='hours',
            field=models.FloatField(default=0, verbose_name='Number of hours'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moduleproperties',
            name='type',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='merovingian.SubjectType', verbose_name='Type of classes'),
            preserve_default=False,
        ),
    ]
