# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-08 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merovingian', '0005_auto_20160203_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='courselevel',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='courseprofile',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='coursetype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='didacticoffer',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='merovingiansettings',
            name='value_en',
        ),
        migrations.RemoveField(
            model_name='module',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='moduletype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='sgroup',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='sgrouptype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='subjectassessment',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='subjecttype',
            name='name_en',
        ),
    ]
