# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-08 16:56
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merovingian', '0006_auto_20171008_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectDifficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
                'verbose_name': 'Class level',
                'verbose_name_plural': 'Class levels',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merovingian.SubjectDifficulty', verbose_name='Class level'),
        ),
    ]
