# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-08 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merovingian', '0007_auto_20171008_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdifficulty',
            name='name_pl',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='subjectdifficulty',
            name='name_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='subjectdifficulty',
            name='name_ua',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
