# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-08 17:20
from __future__ import unicode_literals

from django.db import migrations


def copy_subject_diffuculties(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    SubjectDifficultyOld = apps.get_model('metacortex',
                                          'SubjectDifficulty')
    SubjectDifficultyNew = apps.get_model('merovingian',
                                          'SubjectDifficulty')
    for sd_old in SubjectDifficultyOld.objects.all():
        sd_new = SubjectDifficultyNew()
        sd_new.id = sd_old.id
        sd_new.name_pl = sd_old.name_pl
        sd_new.name_ru = sd_old.name_ru
        sd_new.name_ua = sd_old.name_ua
        sd_new.order = sd_old.order
        sd_new.save()


class Migration(migrations.Migration):

    dependencies = [
        ('merovingian', '0008_auto_20171008_1920'),
        ('metacortex', '0002_auto_20171008_1842')
    ]

    operations = [
        migrations.RunPython(copy_subject_diffuculties),
    ]
