# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-08 17:36
from __future__ import unicode_literals

from django.db import migrations


def copy_subject_diffuculties(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Subject = apps.get_model('merovingian', 'Subject')
    SubjectDifficulty = apps.get_model('merovingian', 'SubjectDifficulty')
    for s in Subject.objects.all():
        ss = s.syllabussubject_set.all()
        if ss and ss[0].subject_difficulty:
            ss_sd = ss[0].subject_difficulty
            sd = SubjectDifficulty.objects.get(id=ss_sd.id)
            s.difficulty = sd
            s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('merovingian', '0009_auto_20171008_1920'),
        ('metacortex', '0002_auto_20171008_1842')
    ]

    operations = [
        migrations.RunPython(copy_subject_diffuculties),
    ]
