# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-10-23 20:49
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0003_leadingdiscipline'),
        ('merovingian', '0010_auto_20171008_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseToLeadingDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implementation', models.IntegerField(verbose_name='Realizacja [%]')),
            ],
            options={
                'verbose_name': 'Kierunek - Dyscyplina wiodąca',
                'verbose_name_plural': 'Kierunki - Dyscypliny wiodące',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='leading_discipline',
            field=models.ManyToManyField(blank=True, to='trinity.LeadingDiscipline'),
        ),
        migrations.AddField(
            model_name='coursetoleadingdiscipline',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merovingian.Course', verbose_name='Kierunek'),
        ),
        migrations.AddField(
            model_name='coursetoleadingdiscipline',
            name='leading_discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trinity.LeadingDiscipline', verbose_name='Dyscyplina wiodąca'),
        ),
    ]
