# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-03-16 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0009_learningoutcomesevaluation_subjecttomodulelearningoutcome'),
        ('merovingian', '0011_auto_20191023_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slos',
            field=models.ManyToManyField(blank=True, through='trinity.SubjectToModuleLearningOutcome', to='trinity.ModuleLearningOutcome', verbose_name='Przedmiotowe efekty uczenia się'),
        ),
    ]
