# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-06-05 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merovingian', '0012_subject_slos'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='ects_classes',
            field=models.FloatField(default=0, verbose_name='ECTS zajęcia'),
        ),
        migrations.AddField(
            model_name='subject',
            name='ects_individual',
            field=models.FloatField(default=0, verbose_name='ECTS praca samodzielna'),
        ),
        migrations.AddField(
            model_name='subject',
            name='hours_individual',
            field=models.FloatField(default=0, verbose_name='Liczba godzin praca samodzielna'),
        ),
    ]
