# Generated by Django 5.2.5 on 2025-08-27 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merovingian', '0002_initial'),
        ('trainman', '0001_initial'),
        ('trinity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('name_pl', models.CharField(max_length=128, null=True)),
                ('name_ua', models.CharField(max_length=128, null=True)),
                ('name_ru', models.CharField(max_length=128, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Evaluation form',
                'verbose_name_plural': 'Evaluation forms',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DidacticMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('name_pl', models.CharField(max_length=128, null=True)),
                ('name_ua', models.CharField(max_length=128, null=True)),
                ('name_ru', models.CharField(max_length=128, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Metoda dydaktyczna',
                'verbose_name_plural': 'Metody dydaktyczne',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ECTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_pl', models.CharField(max_length=255, null=True)),
                ('name_ua', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('flag', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ECTS equivalent in hours',
                'verbose_name_plural': 'ECTS equivalents in hours',
                'ordering': ('is_default', 'name'),
            },
        ),
        migrations.CreateModel(
            name='LectureLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('name_pl', models.CharField(max_length=64, null=True)),
                ('name_ua', models.CharField(max_length=64, null=True)),
                ('name_ru', models.CharField(max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='PracticeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('name_pl', models.CharField(max_length=64, null=True)),
                ('name_ua', models.CharField(max_length=64, null=True)),
                ('name_ru', models.CharField(max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Type of practice',
                'verbose_name_plural': 'Types of practices',
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Syllabus',
                'verbose_name_plural': 'Syllabuses',
            },
        ),
        migrations.CreateModel(
            name='SyllabusYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('read_only', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Syllabus year',
                'verbose_name_plural': 'Syllabuses years',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusToECTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('ects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metacortex.ects')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_to_ects', to='metacortex.syllabus')),
            ],
            options={
                'ordering': ('-ects__is_default', 'ects__order', 'ects__name'),
            },
        ),
        migrations.AddField(
            model_name='syllabus',
            name='ectss',
            field=models.ManyToManyField(blank=True, through='metacortex.SyllabusToECTS', to='metacortex.ects'),
        ),
        migrations.CreateModel(
            name='SyllabusModule',
            fields=[
                ('syllabus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metacortex.syllabus')),
                ('module_description', models.TextField(blank=True, verbose_name='Module description')),
                ('module_description_pl', models.TextField(blank=True, null=True, verbose_name='Module description')),
                ('module_description_ua', models.TextField(blank=True, null=True, verbose_name='Module description')),
                ('module_description_ru', models.TextField(blank=True, null=True, verbose_name='Module description')),
                ('additional_information', models.TextField(blank=True, verbose_name='Additional remarks')),
                ('additional_information_pl', models.TextField(blank=True, null=True, verbose_name='Additional remarks')),
                ('additional_information_ua', models.TextField(blank=True, null=True, verbose_name='Additional remarks')),
                ('additional_information_ru', models.TextField(blank=True, null=True, verbose_name='Additional remarks')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_coordinator', to='trainman.teacher', verbose_name='Coordinator')),
                ('lecture_languages', models.ManyToManyField(blank=True, related_name='lecturelanguages', to='metacortex.lecturelanguage', verbose_name='Languages')),
                ('loes', models.ManyToManyField(blank=True, to='trinity.learningoutcomesevaluation', verbose_name='Sposoby weryfikacji i oceny efektów uczenia się')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='merovingian.module')),
                ('unit_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_source', to='trainman.department', verbose_name='Source unit (the one that the module is offered by)')),
                ('unit_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_target', to='trainman.department', verbose_name='Target unit (the one that the module is offered for)')),
            ],
            options={
                'verbose_name': 'Module syllabus',
                'verbose_name_plural': 'Module syllabuses',
                'ordering': ['module__name'],
            },
            bases=('metacortex.syllabus',),
        ),
        migrations.CreateModel(
            name='SyllabusPractice',
            fields=[
                ('syllabus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metacortex.syllabus')),
                ('learning_outcomes_verification', models.TextField(blank=True, verbose_name='Sposób weryfikacji efektów kształcenia')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_pl', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ua', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('education_effects', models.TextField(blank=True, verbose_name='Additional learning outcomes')),
                ('education_effects_pl', models.TextField(blank=True, null=True, verbose_name='Additional learning outcomes')),
                ('education_effects_ua', models.TextField(blank=True, null=True, verbose_name='Additional learning outcomes')),
                ('education_effects_ru', models.TextField(blank=True, null=True, verbose_name='Additional learning outcomes')),
                ('additional_information', models.TextField(blank=True, verbose_name='Additional remarks')),
                ('additional_information_pl', models.TextField(blank=True, null=True, verbose_name='Additional remarks')),
                ('additional_information_ua', models.TextField(blank=True, null=True, verbose_name='Additional remarks')),
                ('additional_information_ru', models.TextField(blank=True, null=True, verbose_name='Additional remarks')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merovingian.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainman.teacher')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metacortex.practicetype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Practice syllabus',
                'verbose_name_plural': 'Practice syllabuses',
                'ordering': ['subject__name'],
            },
            bases=('metacortex.syllabus', models.Model),
        ),
        migrations.CreateModel(
            name='SyllabusSubject',
            fields=[
                ('syllabus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metacortex.syllabus')),
                ('learning_outcomes_verification', models.TextField(blank=True, verbose_name='Sposób weryfikacji efektów kształcenia')),
                ('additional_name', models.CharField(blank=True, max_length=255, verbose_name='Title of course or additional information regarding the course name')),
                ('additional_name_pl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of course or additional information regarding the course name')),
                ('additional_name_ua', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of course or additional information regarding the course name')),
                ('additional_name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of course or additional information regarding the course name')),
                ('initial_requirements', models.TextField(blank=True, verbose_name='Prerequisities')),
                ('initial_requirements_pl', models.TextField(blank=True, null=True, verbose_name='Prerequisities')),
                ('initial_requirements_ua', models.TextField(blank=True, null=True, verbose_name='Prerequisities')),
                ('initial_requirements_ru', models.TextField(blank=True, null=True, verbose_name='Prerequisities')),
                ('literature', models.TextField(blank=True, verbose_name='Reading list')),
                ('literature_pl', models.TextField(blank=True, null=True, verbose_name='Reading list')),
                ('literature_ua', models.TextField(blank=True, null=True, verbose_name='Reading list')),
                ('literature_ru', models.TextField(blank=True, null=True, verbose_name='Reading list')),
                ('subjects_scope', models.TextField(blank=True, verbose_name='List of topics')),
                ('subjects_scope_pl', models.TextField(blank=True, null=True, verbose_name='List of topics')),
                ('subjects_scope_ua', models.TextField(blank=True, null=True, verbose_name='List of topics')),
                ('subjects_scope_ru', models.TextField(blank=True, null=True, verbose_name='List of topics')),
                ('assessment_conditions', models.TextField(blank=True, null=True, verbose_name='Assessment conditions')),
                ('additional_information', models.TextField(blank=True, verbose_name='Additional remarks')),
                ('additional_information_pl', models.TextField(blank=True, null=True, verbose_name='Additional remarks')),
                ('additional_information_ua', models.TextField(blank=True, null=True, verbose_name='Additional remarks')),
                ('additional_information_ru', models.TextField(blank=True, null=True, verbose_name='Additional remarks')),
                ('education_effects', models.TextField(blank=True, verbose_name='Additional learning outcomes')),
                ('education_effects_pl', models.TextField(blank=True, null=True, verbose_name='Additional learning outcomes')),
                ('education_effects_ua', models.TextField(blank=True, null=True, verbose_name='Additional learning outcomes')),
                ('education_effects_ru', models.TextField(blank=True, null=True, verbose_name='Additional learning outcomes')),
                ('assessment_forms', models.ManyToManyField(blank=True, to='metacortex.assessmentform', verbose_name='Evaluation form')),
                ('didactic_methods', models.ManyToManyField(blank=True, to='metacortex.didacticmethod', verbose_name='Teaching methods')),
                ('module_learning_outcomes', models.ManyToManyField(blank=True, to='trinity.modulelearningoutcome', verbose_name='Module learning outcomes')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merovingian.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainman.teacher')),
            ],
            options={
                'verbose_name': 'Subject syllabus',
                'verbose_name_plural': 'Subject syllabuses',
                'ordering': ['subject__name'],
            },
            bases=('metacortex.syllabus', models.Model),
        ),
    ]
