# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-08 16:42
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metacortex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentform',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='didacticmethodmajor',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='didacticmethodminor',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='ects',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='lecturelanguage',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='practicetype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='subjectdifficulty',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='syllabusmodule',
            name='additional_information_en',
        ),
        migrations.RemoveField(
            model_name='syllabusmodule',
            name='module_description_en',
        ),
        migrations.RemoveField(
            model_name='syllabuspractice',
            name='additional_information_en',
        ),
        migrations.RemoveField(
            model_name='syllabuspractice',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='syllabuspractice',
            name='education_effects_en',
        ),
        migrations.RemoveField(
            model_name='syllabussubject',
            name='additional_information_en',
        ),
        migrations.RemoveField(
            model_name='syllabussubject',
            name='additional_name_en',
        ),
        migrations.RemoveField(
            model_name='syllabussubject',
            name='education_effects_en',
        ),
        migrations.RemoveField(
            model_name='syllabussubject',
            name='initial_requirements_en',
        ),
        migrations.RemoveField(
            model_name='syllabussubject',
            name='literature_en',
        ),
        migrations.RemoveField(
            model_name='syllabussubject',
            name='subjects_scope_en',
        ),
        migrations.AlterField(
            model_name='syllabuspractice',
            name='additional_information',
            field=models.TextField(blank=True, verbose_name='Additional remarks'),
        ),
        migrations.AlterField(
            model_name='syllabuspractice',
            name='additional_information_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Additional remarks'),
        ),
        migrations.AlterField(
            model_name='syllabuspractice',
            name='additional_information_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Additional remarks'),
        ),
        migrations.AlterField(
            model_name='syllabuspractice',
            name='additional_information_ua',
            field=models.TextField(blank=True, null=True, verbose_name='Additional remarks'),
        ),
        migrations.AlterField(
            model_name='syllabuspractice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='syllabuspractice',
            name='description_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='syllabuspractice',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='syllabuspractice',
            name='description_ua',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='syllabuspractice',
            name='education_effects',
            field=models.TextField(blank=True, verbose_name='Additional learning outcomes'),
        ),
        migrations.AlterField(
            model_name='syllabuspractice',
            name='education_effects_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Additional learning outcomes'),
        ),
        migrations.AlterField(
            model_name='syllabuspractice',
            name='education_effects_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Additional learning outcomes'),
        ),
        migrations.AlterField(
            model_name='syllabuspractice',
            name='education_effects_ua',
            field=models.TextField(blank=True, null=True, verbose_name='Additional learning outcomes'),
        ),
        migrations.AlterField(
            model_name='syllabuspractice',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metacortex.PracticeType', verbose_name='Type'),
        ),
    ]
