# Generated by Django 5.2.5 on 2025-08-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metacortex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentform',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='didacticmethod',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ects',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lecturelanguage',
            name='name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='practicetype',
            name='name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='syllabusmodule',
            name='additional_information_en',
            field=models.TextField(blank=True, null=True, verbose_name='Additional remarks'),
        ),
        migrations.AddField(
            model_name='syllabusmodule',
            name='module_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Module description'),
        ),
        migrations.AddField(
            model_name='syllabuspractice',
            name='additional_information_en',
            field=models.TextField(blank=True, null=True, verbose_name='Additional remarks'),
        ),
        migrations.AddField(
            model_name='syllabuspractice',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='syllabuspractice',
            name='education_effects_en',
            field=models.TextField(blank=True, null=True, verbose_name='Additional learning outcomes'),
        ),
        migrations.AddField(
            model_name='syllabussubject',
            name='additional_information_en',
            field=models.TextField(blank=True, null=True, verbose_name='Additional remarks'),
        ),
        migrations.AddField(
            model_name='syllabussubject',
            name='additional_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of course or additional information regarding the course name'),
        ),
        migrations.AddField(
            model_name='syllabussubject',
            name='education_effects_en',
            field=models.TextField(blank=True, null=True, verbose_name='Additional learning outcomes'),
        ),
        migrations.AddField(
            model_name='syllabussubject',
            name='initial_requirements_en',
            field=models.TextField(blank=True, null=True, verbose_name='Prerequisities'),
        ),
        migrations.AddField(
            model_name='syllabussubject',
            name='literature_en',
            field=models.TextField(blank=True, null=True, verbose_name='Reading list'),
        ),
        migrations.AddField(
            model_name='syllabussubject',
            name='subjects_scope_en',
            field=models.TextField(blank=True, null=True, verbose_name='List of topics'),
        ),
    ]
