# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-10-23 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metacortex', '0002_auto_20171008_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabussubject',
            name='subject_difficulty',
        ),
        migrations.DeleteModel(
            name='SubjectDifficulty',
        ),
    ]
