# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-03-21 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metacortex', '0003_auto_20191023_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabustoects',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
