# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-03-22 21:39
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metacortex', '0004_syllabustoects_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='didacticmethodminor',
            name='major_didactic_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='didactic_methods', to='metacortex.DidacticMethodMajor', verbose_name='Major teaching method'),
        ),
        migrations.AlterField(
            model_name='syllabustoects',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_to_ects', to='metacortex.Syllabus'),
        ),
    ]
