# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-03-22 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metacortex', '0005_auto_20200322_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='didacticmethodmajor',
            name='name_pl',
        ),
        migrations.RemoveField(
            model_name='didacticmethodmajor',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='didacticmethodmajor',
            name='name_ua',
        ),
        migrations.RemoveField(
            model_name='didacticmethodminor',
            name='major_didactic_method',
        ),
        migrations.AddField(
            model_name='didacticmethodminor',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
