# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-03-22 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metacortex', '0006_auto_20200322_2241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DidacticMethodMinor',
            new_name='DidacticMethod',
        ),
        migrations.DeleteModel(
            name='DidacticMethodMajor',
        ),
    ]
