# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-03-23 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0010_auto_20200321_2033'),
        ('metacortex', '0007_auto_20200322_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='didacticmethod',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Metoda dydaktyczna', 'verbose_name_plural': 'Metody dydaktyczne'},
        ),
        migrations.AddField(
            model_name='syllabusmodule',
            name='loes',
            field=models.ManyToManyField(blank=True, to='trinity.LearningOutcomesEvaluation', verbose_name='Sposoby weryfikacji i oceny efektów uczenia się'),
        ),
        migrations.AddField(
            model_name='syllabusmodule',
            name='program_content',
            field=models.TextField(blank=True, verbose_name='Treści programowe'),
        ),
    ]
