# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-03-23 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metacortex', '0008_auto_20200323_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabusmodule',
            name='program_content',
        ),
    ]
