# Generated by Django 5.2.5 on 2025-08-27 15:24

import django.db.models.deletion
from django.db import migrations, models

import apps.syjon.lib.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merovingian', '0001_initial'),
        ('trainman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_pl', models.CharField(max_length=255, null=True)),
                ('name_ua', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Area of education',
                'verbose_name_plural': 'Areas of education',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EducationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_pl', models.CharField(max_length=255, null=True)),
                ('name_ua', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Education category',
                'verbose_name_plural': 'Education categories',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='EducationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_pl', models.CharField(max_length=255, null=True)),
                ('name_ua', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Field of science',
                'verbose_name_plural': 'Fields of science',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_pl', models.CharField(max_length=255, null=True)),
                ('name_ua', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Area of knowledge',
                'verbose_name_plural': 'Areas of knowledge',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LeadingDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Dyscyplina wiodąca',
                'verbose_name_plural': 'Dyscypliny wiodące',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LearningOutcomeAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Aspekt charakterystyki',
                'verbose_name_plural': 'Aspekty charakterystyk',
            },
        ),
        migrations.CreateModel(
            name='LearningOutcomesEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Sposób weryfikacji i oceny efektów uczenia się',
                'verbose_name_plural': 'Sposoby weryfikacji i oceny efektów uczenia się',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AreaLearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('symbol_pl', models.CharField(max_length=16, null=True, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('symbol_ua', models.CharField(max_length=16, null=True, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('symbol_ru', models.CharField(max_length=16, null=True, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('description', models.TextField(validators=[apps.syjon.lib.validators.validate_white_space])),
                ('description_pl', models.TextField(null=True, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('description_ua', models.TextField(null=True, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('description_ru', models.TextField(null=True, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merovingian.courselevel')),
                ('education_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merovingian.courseprofile')),
                ('education_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trinity.educationarea')),
                ('education_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trinity.educationcategory')),
            ],
            options={
                'verbose_name': 'Area learning outcome',
                'verbose_name_plural': 'Area learning outcomes',
                'ordering': ('symbol',),
            },
        ),
        migrations.CreateModel(
            name='EducationDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_pl', models.CharField(max_length=255, null=True)),
                ('name_ua', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('education_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trinity.educationfield')),
            ],
            options={
                'verbose_name': 'Discipline of science',
                'verbose_name_plural': 'Disciplines of science',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='educationfield',
            name='knowledge_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trinity.knowledgearea'),
        ),
        migrations.CreateModel(
            name='LearningOutcomeCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('description', models.TextField(validators=[apps.syjon.lib.validators.validate_white_space])),
                ('level', models.IntegerField()),
                ('aspect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trinity.learningoutcomeaspect')),
                ('education_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trinity.educationcategory')),
            ],
            options={
                'verbose_name': 'Charakterystyka efektu uczenia się',
                'verbose_name_plural': 'Charakterystyki efektów uczenia się',
                'ordering': ('symbol',),
            },
        ),
        migrations.CreateModel(
            name='CourseLearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('symbol_pl', models.CharField(max_length=16, null=True, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('symbol_ua', models.CharField(max_length=16, null=True, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('symbol_ru', models.CharField(max_length=16, null=True, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('description', models.TextField(validators=[apps.syjon.lib.validators.validate_white_space])),
                ('description_pl', models.TextField(null=True, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('description_ua', models.TextField(null=True, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('description_ru', models.TextField(null=True, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('alos', models.ManyToManyField(related_name='clos', to='trinity.arealearningoutcome')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clos', to='merovingian.course')),
                ('education_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trinity.educationcategory')),
                ('locs', models.ManyToManyField(related_name='locs', to='trinity.learningoutcomecharacteristic')),
            ],
            options={
                'verbose_name': 'Course learning outcome',
                'verbose_name_plural': 'Course learning outcomes',
                'ordering': ('symbol',),
            },
        ),
        migrations.CreateModel(
            name='ModuleLearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('symbol_pl', models.CharField(max_length=16, null=True, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('symbol_ua', models.CharField(max_length=16, null=True, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('symbol_ru', models.CharField(max_length=16, null=True, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('description', models.TextField(validators=[apps.syjon.lib.validators.validate_white_space])),
                ('description_pl', models.TextField(null=True, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('description_ua', models.TextField(null=True, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('description_ru', models.TextField(null=True, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('clos', models.ManyToManyField(related_name='mlos', to='trinity.courselearningoutcome')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlos', to='merovingian.module')),
            ],
            options={
                'verbose_name': 'Module learning outcome',
                'verbose_name_plural': 'Module learning outcomes',
                'ordering': ('symbol',),
            },
        ),
        migrations.CreateModel(
            name='SubjectToModuleLearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loes', models.ManyToManyField(to='trinity.learningoutcomesevaluation')),
                ('mlo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_to_slos', to='trinity.modulelearningoutcome')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_to_slos', to='merovingian.subject')),
            ],
            options={
                'verbose_name': 'Przedmiotowy efekt uczenia się',
                'verbose_name_plural': 'Przedmiotowe efekty uczenia się',
                'ordering': ('mlo__symbol',),
            },
        ),
        migrations.CreateModel(
            name='TrinityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(blank=True, to='merovingian.course')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trainman.userprofile', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administrators',
            },
        ),
    ]
