# Generated by Django 5.2.5 on 2025-08-29 15:35

import apps.syjon.lib.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arealearningoutcome',
            name='description_en',
            field=models.TextField(null=True, validators=[apps.syjon.lib.validators.validate_white_space]),
        ),
        migrations.AddField(
            model_name='arealearningoutcome',
            name='symbol_en',
            field=models.CharField(max_length=16, null=True, validators=[apps.syjon.lib.validators.validate_white_space]),
        ),
        migrations.AddField(
            model_name='courselearningoutcome',
            name='description_en',
            field=models.TextField(null=True, validators=[apps.syjon.lib.validators.validate_white_space]),
        ),
        migrations.AddField(
            model_name='courselearningoutcome',
            name='symbol_en',
            field=models.CharField(max_length=16, null=True, validators=[apps.syjon.lib.validators.validate_white_space]),
        ),
        migrations.AddField(
            model_name='educationarea',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationdiscipline',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationfield',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='knowledgearea',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modulelearningoutcome',
            name='description_en',
            field=models.TextField(null=True, validators=[apps.syjon.lib.validators.validate_white_space]),
        ),
        migrations.AddField(
            model_name='modulelearningoutcome',
            name='symbol_en',
            field=models.CharField(max_length=16, null=True, validators=[apps.syjon.lib.validators.validate_white_space]),
        ),
    ]
