# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-08 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arealearningoutcome',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='arealearningoutcome',
            name='symbol_en',
        ),
        migrations.RemoveField(
            model_name='courselearningoutcome',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='courselearningoutcome',
            name='symbol_en',
        ),
        migrations.RemoveField(
            model_name='educationarea',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='educationcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='educationdiscipline',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='educationfield',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='knowledgearea',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='modulelearningoutcome',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='modulelearningoutcome',
            name='symbol_en',
        ),
    ]
