# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-10-23 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0002_auto_20171008_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadingDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Dyscyplina wiodąca',
                'verbose_name_plural': 'Dyscypliny wiodące',
                'ordering': ('name',),
            },
        ),
    ]
