# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-10-26 09:54
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import apps.syjon.lib.validators


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0003_leadingdiscipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningOutcomeCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16, validators=[apps.syjon.lib.validators.validate_white_space])),
                ('description', models.TextField(validators=[apps.syjon.lib.validators.validate_white_space])),
                ('level', models.IntegerField()),
                ('education_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trinity.EducationCategory')),
                ('leading_discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trinity.LeadingDiscipline')),
            ],
        ),
        migrations.AddField(
            model_name='courselearningoutcome',
            name='locs',
            field=models.ManyToManyField(related_name='clos', to='trinity.LearningOutcomeCharacteristic'),
        ),
    ]
