# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-10-26 09:59
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merovingian', '0011_auto_20191023_2249'),
        ('trinity', '0004_auto_20191026_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningoutcomecharacteristic',
            name='level',
        ),
        migrations.AddField(
            model_name='learningoutcomecharacteristic',
            name='education_level',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='merovingian.CourseLevel'),
            preserve_default=False,
        ),
    ]
