# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-10-26 18:15
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0005_auto_20191026_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningOutcomeAspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Aspekt charakterystyki',
                'verbose_name_plural': 'Aspekty charakterystyk',
            },
        ),
        migrations.AlterModelOptions(
            name='learningoutcomecharacteristic',
            options={'ordering': ('symbol',), 'verbose_name': 'Charakterystyka efektu uczenia się', 'verbose_name_plural': 'Charakterystyki efektów uczenia się'},
        ),
        migrations.RemoveField(
            model_name='learningoutcomecharacteristic',
            name='leading_discipline',
        ),
        migrations.AddField(
            model_name='learningoutcomecharacteristic',
            name='aspect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trinity.LearningOutcomeAspect'),
        ),
    ]
