# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-02-26 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0006_auto_20191026_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselearningoutcome',
            name='locs',
            field=models.ManyToManyField(related_name='locs', to='trinity.LearningOutcomeCharacteristic'),
        ),
        migrations.AlterField(
            model_name='learningoutcomecharacteristic',
            name='education_level',
            field=models.IntegerField(),
        ),
    ]
