# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-02-26 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0007_auto_20200226_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningoutcomecharacteristic',
            old_name='education_level',
            new_name='level',
        ),
    ]
