# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-03-16 15:17
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merovingian', '0011_auto_20191023_2249'),
        ('trinity', '0008_auto_20200226_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningOutcomesEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectToModuleLearningOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loes', models.ManyToManyField(related_name='loes', to='trinity.LearningOutcomesEvaluation')),
                ('mlo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlo', to='trinity.ModuleLearningOutcome')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slo', to='merovingian.Subject')),
            ],
            options={
                'verbose_name': 'Przedmiotowy efekt uczenia się',
                'verbose_name_plural': 'Przedmiotowe efekty uczenia się',
            },
        ),
    ]
