# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-03-21 19:33
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0009_learningoutcomesevaluation_subjecttomodulelearningoutcome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningoutcomesevaluation',
            options={'verbose_name': 'Sposób weryfikacji i oceny efektów uczenia się', 'verbose_name_plural': 'Sposoby weryfikacji i oceny efektów uczenia się'},
        ),
        migrations.AlterField(
            model_name='subjecttomodulelearningoutcome',
            name='loes',
            field=models.ManyToManyField(to='trinity.LearningOutcomesEvaluation'),
        ),
        migrations.AlterField(
            model_name='subjecttomodulelearningoutcome',
            name='mlo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_to_slos', to='trinity.ModuleLearningOutcome'),
        ),
        migrations.AlterField(
            model_name='subjecttomodulelearningoutcome',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_to_slos', to='merovingian.Subject'),
        ),
    ]
